export const IPC_CHANNELS = {
  LIBRARY_OPEN_FOLDER: "library:openFolder",
  LIBRARY_CLOSE_FOLDER: "library:closeFolder",
  LIBRARY_LIST_FOLDERS: "library:listFolders",
  LIBRARY_LIST_FILES: "library:listFiles",
  LIBRARY_OPEN_FILE: "library:openFile",
  LIBRARY_SAVE_FILE: "library:saveFile",
  LIBRARY_CREATE_FILE: "library:createFile",
  LIBRARY_RUN_OPERATION: "library:runOperation",
  LIBRARY_RUN_QUERY: "library:runQuery",
  LIBRARY_EXPORT_FILE: "library:exportFile",
  LIBRARY_SEARCH: "library:search",
  LIBRARY_LIST_VERSIONS: "library:listVersions",
  LIBRARY_RESTORE_VERSION: "library:restoreVersion",
  REGISTRY_LIST_MODULES: "registry:listModules",
  NOTES_RENDER_PREVIEW: "notes:renderPreview",
  AI_STATUS: "ai:status",
  AI_CHAT: "ai:chat",
  AI_RUN_TOOL: "ai:runTool",
  PDF_READ_BYTES: "pdf:readBytes",
  IMAGE_READ_BYTES: "image:readBytes",
} as const;
